cache:
  paths:
    - source/vendor

stages:
  - build
  - package

build:composer:
  image: composer:latest
  stage: build
  script:
    - cd source
    - composer install --no-interaction --no-dev
      --ignore-platform-req=ext-bcmath
      --ignore-platform-req=ext-gd
      --ignore-platform-req=ext-gmp
      --ignore-platform-req=ext-intl
      --ignore-platform-req=ext-redis
  artifacts:
    paths:
      - source/vendor/
    expire_in: 1 week

build:yarn:
  image: node:16-bullseye
  stage: build
  before_script:
    - apt update && apt install php -y
  script:
    - cd source
    - yarn install
    - yarn run production
  artifacts:
    paths:
      - source/bootstrap/cache/packages.php
      - source/bootstrap/cache/services.php
      - source/node_modules/
      - source/public/css/
      - source/public/fonts/
      - source/public/js/
      - source/public/mix-manifest.json
    expire_in: 1 week

package:
  stage: package
  image: debian:stable
  artifacts:
    paths:
    - "*.deb"
  before_script:
    - apt-get update && apt-get install build-essential debhelper-compat -y
  script:
    - cd package
    - dpkg-buildpackage -uc -us
